// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainPanelTitle = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_MainPanelTitle, lv_pct(100));
    lv_obj_set_height(ui_MainPanelTitle, lv_pct(14));
    lv_obj_set_align(ui_MainPanelTitle, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MainPanelTitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanelTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainPanelTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainIconWiFi = lv_label_create(ui_MainPanelTitle);
    lv_obj_set_width(ui_MainIconWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainIconWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainIconWiFi, -5);
    lv_obj_set_y(ui_MainIconWiFi, 0);
    lv_obj_set_align(ui_MainIconWiFi, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MainIconWiFi, "有");
    lv_obj_set_style_text_color(ui_MainIconWiFi, lv_color_hex(0xE78429), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainIconWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainIconWiFi, &ui_font_IconWiFi24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelStatus = lv_label_create(ui_MainPanelTitle);
    lv_obj_set_width(ui_MainLabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelStatus, 3);
    lv_obj_set_y(ui_MainLabelStatus, 1);
    lv_obj_set_align(ui_MainLabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabelStatus, "1901");
    lv_obj_set_style_text_color(ui_MainLabelStatus, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelStatus, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelNotification = lv_label_create(ui_MainPanelTitle);
    lv_obj_set_width(ui_MainLabelNotification, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabelNotification, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelNotification, 0);
    lv_obj_set_y(ui_MainLabelNotification, 2);
    lv_obj_set_align(ui_MainLabelNotification, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabelNotification, "09:29");
    lv_obj_add_flag(ui_MainLabelNotification, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_MainLabelNotification, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelNotification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelNotification, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelWiFiInfo = lv_label_create(ui_MainPanelTitle);
    lv_obj_set_width(ui_MainLabelWiFiInfo, 80);
    lv_obj_set_height(ui_MainLabelWiFiInfo, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_MainLabelWiFiInfo, 25);
    lv_obj_set_y(ui_MainLabelWiFiInfo, 1);
    lv_obj_set_align(ui_MainLabelWiFiInfo, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_MainLabelWiFiInfo, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_MainLabelWiFiInfo, "1901");
    lv_obj_set_style_text_color(ui_MainLabelWiFiInfo, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelWiFiInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelWiFiInfo, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainIconBat = lv_label_create(ui_MainPanelTitle);
    lv_obj_set_width(ui_MainIconBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainIconBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainIconBat, 5);
    lv_obj_set_y(ui_MainIconBat, 1);
    lv_obj_set_align(ui_MainIconBat, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_MainIconBat, "0");
    lv_obj_set_style_text_color(ui_MainIconBat, lv_color_hex(0x43B131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainIconBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainIconBat, &ui_font_IconBat24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelBat = lv_label_create(ui_MainPanelTitle);
    lv_obj_set_width(ui_MainLabelBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabelBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelBat, -25);
    lv_obj_set_y(ui_MainLabelBat, 1);
    lv_obj_set_align(ui_MainLabelBat, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_MainLabelBat, "79%");
    lv_obj_set_style_text_color(ui_MainLabelBat, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelBat, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLoading = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_MainLoading, lv_pct(100));
    lv_obj_set_height(ui_MainLoading, lv_pct(86));
    lv_obj_set_align(ui_MainLoading, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_MainLoading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainLoading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainLoading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainLoading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainLoading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelLoad = lv_label_create(ui_MainLoading);
    lv_obj_set_width(ui_MainLabelLoad, 180);
    lv_obj_set_height(ui_MainLabelLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelLoad, 0);
    lv_obj_set_y(ui_MainLabelLoad, 120);
    lv_obj_set_align(ui_MainLabelLoad, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MainLabelLoad, "xiaozhi.me \n063774");
    lv_obj_set_style_text_color(ui_MainLabelLoad, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelLoad, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainSpinLoad = lv_spinner_create(ui_MainLoading);
    //lv_spinner_set_anim_params(ui_MainSpinLoad, 1000, 90);
    lv_obj_set_width(ui_MainSpinLoad, 70);
    lv_obj_set_height(ui_MainSpinLoad, 70);
    lv_obj_set_x(ui_MainSpinLoad, 0);
    lv_obj_set_y(ui_MainSpinLoad, -20);
    lv_obj_set_align(ui_MainSpinLoad, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainSpinLoad, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_opa(ui_MainSpinLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_MainSpinLoad, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainSpinLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainSpinLoad, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MainSpinLoad, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MainSpinLoad, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MainSpinLoad, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MainPanelSleep = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_MainPanelSleep, lv_pct(100));
    lv_obj_set_height(ui_MainPanelSleep, lv_pct(86));
    lv_obj_set_align(ui_MainPanelSleep, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MainPanelSleep, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MainPanelSleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanelSleep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainPanelSleep, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainImageMic1 = lv_image_create(ui_MainPanelSleep);
    lv_image_set_src(ui_MainImageMic1, &ui_img_1590408947);
    lv_obj_set_width(ui_MainImageMic1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainImageMic1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainImageMic1, lv_pct(-40));
    lv_obj_set_y(ui_MainImageMic1, lv_pct(24));
    lv_obj_set_align(ui_MainImageMic1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainImageMic1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MainImageMic1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainLabelComm = lv_label_create(ui_MainPanelSleep);
    lv_obj_set_width(ui_MainLabelComm, lv_pct(80));
    lv_obj_set_height(ui_MainLabelComm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelComm, lv_pct(8));
    lv_obj_set_y(ui_MainLabelComm, lv_pct(25));
    lv_obj_set_align(ui_MainLabelComm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabelComm, "语音输入”你好小智“，唤醒我");
    lv_obj_set_style_text_color(ui_MainLabelComm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelComm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelComm, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainIconEmoji = lv_image_create(ui_MainPanelSleep);
    lv_image_set_src(ui_MainIconEmoji, &ui_img_image_sleep_png);
    lv_obj_set_width(ui_MainIconEmoji, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainIconEmoji, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainIconEmoji, lv_pct(0));
    lv_obj_set_y(ui_MainIconEmoji, lv_pct(-20));
    lv_obj_set_align(ui_MainIconEmoji, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainIconEmoji, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MainIconEmoji, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanelComm = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_MainPanelComm, lv_pct(100));
    lv_obj_set_height(ui_MainPanelComm, lv_pct(86));
    lv_obj_set_x(ui_MainPanelComm, -2);
    lv_obj_set_y(ui_MainPanelComm, 2);
    lv_obj_set_align(ui_MainPanelComm, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_MainPanelComm, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MainPanelComm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanelComm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanelComm, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanelComm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainPanelComm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainDecorationRobotComm = lv_image_create(ui_MainPanelComm);
    lv_image_set_src(ui_MainDecorationRobotComm, &ui_img_2129536719);
    lv_obj_set_width(ui_MainDecorationRobotComm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainDecorationRobotComm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainDecorationRobotComm, lv_pct(18));
    lv_obj_set_y(ui_MainDecorationRobotComm, lv_pct(30));
    lv_obj_set_align(ui_MainDecorationRobotComm, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MainDecorationRobotComm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MainDecorationRobotComm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainDecorationUserComm = lv_image_create(ui_MainPanelComm);
    lv_image_set_src(ui_MainDecorationUserComm, &ui_img_363796412);
    lv_obj_set_width(ui_MainDecorationUserComm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainDecorationUserComm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_MainDecorationUserComm, -44);
    lv_obj_set_x(ui_MainDecorationUserComm, lv_pct(-18));
    lv_obj_set_align(ui_MainDecorationUserComm, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MainDecorationUserComm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MainDecorationUserComm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanelUserComm = lv_obj_create(ui_MainPanelComm);
    lv_obj_set_width(ui_MainPanelUserComm, 60);
    lv_obj_set_height(ui_MainPanelUserComm, 40);
    lv_obj_set_x(ui_MainPanelUserComm, lv_pct(-22));
    lv_obj_set_y(ui_MainPanelUserComm, lv_pct(-25));
    lv_obj_set_align(ui_MainPanelUserComm, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_MainPanelUserComm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanelUserComm, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanelUserComm, lv_color_hex(0x95EC69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanelUserComm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainPanelUserComm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelUserComm = lv_label_create(ui_MainPanelUserComm);
    lv_obj_set_width(ui_MainLabelUserComm, 40);
    lv_obj_set_height(ui_MainLabelUserComm, 18);
    lv_obj_set_x(ui_MainLabelUserComm, 5);
    lv_obj_set_y(ui_MainLabelUserComm, 0);
    lv_obj_set_align(ui_MainLabelUserComm, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MainLabelUserComm, "。。");
    lv_obj_set_style_text_color(ui_MainLabelUserComm, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelUserComm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelUserComm, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainImageUser = lv_image_create(ui_MainPanelComm);
    lv_image_set_src(ui_MainImageUser, &ui_img_image_user2_png);
    lv_obj_set_width(ui_MainImageUser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainImageUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainImageUser, 14);
    lv_obj_set_y(ui_MainImageUser, lv_pct(-2));
    lv_obj_set_align(ui_MainImageUser, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_MainImageUser, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MainImageUser, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainImageRobot = lv_image_create(ui_MainPanelComm);
    lv_image_set_src(ui_MainImageRobot, &ui_img_382539590);
    lv_obj_set_width(ui_MainImageRobot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainImageRobot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainImageRobot, -9);
    lv_obj_set_y(ui_MainImageRobot, lv_pct(-4));
    lv_obj_set_align(ui_MainImageRobot, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_MainImageRobot, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MainImageRobot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanelRobotComm = lv_obj_create(ui_MainPanelComm);
    lv_obj_set_width(ui_MainPanelRobotComm, 70);
    lv_obj_set_height(ui_MainPanelRobotComm, 42);
    lv_obj_set_x(ui_MainPanelRobotComm, lv_pct(22));
    lv_obj_set_y(ui_MainPanelRobotComm, lv_pct(30));
    lv_obj_set_align(ui_MainPanelRobotComm, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_MainPanelRobotComm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanelRobotComm, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanelRobotComm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanelRobotComm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MainPanelRobotComm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelRobotComm = lv_label_create(ui_MainPanelRobotComm);
    lv_obj_set_width(ui_MainLabelRobotComm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabelRobotComm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelRobotComm, 5);
    lv_obj_set_y(ui_MainLabelRobotComm, 0);
    lv_label_set_text(ui_MainLabelRobotComm, "你好");
    lv_obj_set_style_text_color(ui_MainLabelRobotComm, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainLabelRobotComm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainLabelRobotComm, &ui_font_CN16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
