// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_MainPanelTitle;
lv_obj_t * ui_MainIconWiFi;
lv_obj_t * ui_MainLabelStatus;
lv_obj_t * ui_MainLabelNotification;
lv_obj_t * ui_MainLabelWiFiInfo;
lv_obj_t * ui_MainIconBat;
lv_obj_t * ui_MainLabelBat;
lv_obj_t * ui_MainLoading;
lv_obj_t * ui_MainLabelLoad;
lv_obj_t * ui_MainSpinLoad;
lv_obj_t * ui_MainPanelSleep;
lv_obj_t * ui_MainImageMic1;
lv_obj_t * ui_MainLabelComm;
lv_obj_t * ui_MainIconEmoji;
lv_obj_t * ui_MainPanelComm;
lv_obj_t * ui_MainDecorationRobotComm;
lv_obj_t * ui_MainDecorationUserComm;
lv_obj_t * ui_MainPanelUserComm;
lv_obj_t * ui_MainLabelUserComm;
lv_obj_t * ui_MainImageUser;
lv_obj_t * ui_MainImageRobot;
lv_obj_t * ui_MainPanelRobotComm;
lv_obj_t * ui_MainLabelRobotComm;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMain);
}
