// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_MainPanelTitle;
extern lv_obj_t * ui_MainIconWiFi;
extern lv_obj_t * ui_MainLabelStatus;
extern lv_obj_t * ui_MainLabelNotification;
extern lv_obj_t * ui_MainLabelWiFiInfo;
extern lv_obj_t * ui_MainIconBat;
extern lv_obj_t * ui_MainLabelBat;
extern lv_obj_t * ui_MainLoading;
extern lv_obj_t * ui_MainLabelLoad;
extern lv_obj_t * ui_MainSpinLoad;
extern lv_obj_t * ui_MainPanelSleep;
extern lv_obj_t * ui_MainImageMic1;
extern lv_obj_t * ui_MainLabelComm;
extern lv_obj_t * ui_MainIconEmoji;
extern lv_obj_t * ui_MainPanelComm;
extern lv_obj_t * ui_MainDecorationRobotComm;
extern lv_obj_t * ui_MainDecorationUserComm;
extern lv_obj_t * ui_MainPanelUserComm;
extern lv_obj_t * ui_MainLabelUserComm;
extern lv_obj_t * ui_MainImageUser;
extern lv_obj_t * ui_MainImageRobot;
extern lv_obj_t * ui_MainPanelRobotComm;
extern lv_obj_t * ui_MainLabelRobotComm;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1590408947);    // assets/image/语音.png
LV_IMG_DECLARE(ui_img_image_sleep_png);    // assets/image/sleep.png
LV_IMG_DECLARE(ui_img_2129536719);    // assets/image/triangle-left.png
LV_IMG_DECLARE(ui_img_363796412);    // assets/image/triangle-right.png
LV_IMG_DECLARE(ui_img_image_user2_png);    // assets/image/user2.png
LV_IMG_DECLARE(ui_img_382539590);    // assets/image/Penguin (2).png

// FONTS
LV_FONT_DECLARE(ui_font_CN16);
LV_FONT_DECLARE(ui_font_IconBat24);
LV_FONT_DECLARE(ui_font_IconWiFi24);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
